### ISSUE TITLE
Disappearing inventory and character buttons

### ISSUE THREAD

**Issue by NetherNarwhal** [Interrupt/delverengine#10]
When bringing up the inventory screen, the inventory and character buttons initially show but will disappear if interacted with (exception being you able to click on the character button once). The buttons will not reappear when you go back into the inventory screens. This persists until the application is restarted. You may still use the inventory, but there is no way to see your character information after the first time without restarting.

In both the `InventoryScreen.java` and `CharacterScreen.java` makeContent methods I tried changing the following `clear()` calls to `clearChildren()` and `reset()`. No luck.
```
outerWindow.clear();
contentTable.clear();
```
The lines for turning debug on for outerWindow also disappears when the buttons do, even though the contentTable is still shown. The only workaround I have found is to recreate the outerWindow right below that:
```
outerWindow.clear();
contentTable.clear();
// This fixes it for some reason when even reset won't.
outerWindow = new Table();
```
Do this for both `InventoryScreen.java` and `CharacterScreen.java` and things work again.

**Comment by Interrupt** [comment]
Fixed in 9894432b1f107efe3924279e9c3cdf9371f9576d
