### ISSUE TITLE
Add Formater And/Or Linter

### ISSUE THREAD

**Issue by PythooonUser** [Interrupt/delverengine#102]
## Summary
As the project ventures into the realms of open-source it encounters many different developers using a variety of operating systems, editors and naming conventions (and `{}` bracket style religions).

Therefore, and also to remove any whitespace wars, the project could adopt a global editor configuration and linter/formatter solution.

**Solutions:**
- [Editor Config](https://editorconfig.org/)
- [Prettier](https://prettier.io/)

There might be others, maybe more Java related, please add to the list.

**Comment by PythooonUser** [comment]
Interesting to note: Prettier is an *opiniated formatter*. Therefore, it takes away the decision of a certain style :D

**Comment by evrimoztamur** [comment]
I think the primary constituents of a styling convention for us would concern tabs/spaces and bracket styling. If we are to use a standard procedure then I vote for Editor Config (because it comes with default support for the IntelliJ suite).
