### ISSUE TITLE
Switch To JSON Configuration Files

### ISSUE THREAD

**Issue by PythooonUser** [Interrupt/delverengine#116]
## Summary
~~With the new JSON schemas for configuration files it would be nice to be able to actually use them. Currently (as `.dat` is not a recognized default JSON format) one needs to set JSON as language in the IDE of choice for each configuration file.~~

~~It would be easier when these configuration files would be standardized using the `.json` file extension, so that the schemas can be used without any hassle.~~

~~Probably a backwards compatibility step needs to be addressed here (for loading old `.dat` formats).~~

In addition, is there a plan to roll out the schemas to modders (meaning to include them in the base game)? Because schemas (as far as I know) need to be referenced locally by a relative path. And currently the schemas reside in the top-level project folder., which is *not* part of the Steam build?!

**Comment by joshuaskelly** [comment]
This seems like it would be a big compatibility issue. It's pretty easy to configure a project to associate `.dat` with `.json`

**Comment by PythooonUser** [comment]
Okay, fair enough. Then only the last point remains valid.
