### ISSUE TITLE
JSON Schemas Broken

### ISSUE THREAD

**Issue by PythooonUser** [Interrupt/delverengine#117]
## Summary
A definition is missing in the JSON schemas which causes the entire intellisense to break.

`$ref '/definitions/TriggerLike' in '/delverengine/jsonschema/current/Interfaces.schema.json' can not be resolved.`

**Comment by joshuaskelly** [comment]
Apologies. I try to test on both IntelliJ and VSCode. Apparently IntelliJ is more resilient for these kinds of errors.

**Comment by PythooonUser** [comment]
Okay, using the schemas by defining them in `.vscode/settings.json` works as intended. Closing.
