### ISSUE TITLE
Setup and building on macos with visual studio code

### ISSUE THREAD

**Issue by jmickle66666666** [Interrupt/delverengine#13]
I'm currently setting up this project and thought it may be useful for future users to document my setup process. I'm using MacOS and Visual Studio Code.

* Install the JDK from here (https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html)
* Install java8 with homebrew: `brew cask install homebrew/cask-versions/java8`
* Install gradle 2.14 with homebrew: `brew install gradle@2.14` 
* * Note: newer versions of gradle may not work
* Open the `delverengine` folder in Code
* Open the terminal in Code and run `sh build.sh` to build

You can now run Delver by navigating to the DungeoneerDesktop/ directory and running `gradle run`

**Comment by joshuaskelly** [comment]
Should this info live in the wiki? I can see documenting various dev setups being useful.

**Comment by jmickle66666666** [comment]
`tasks.json` for vs code, tasks for building, and running both editor and game.
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "sh build.sh",
            "problemMatcher": [],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "label": "run game",
            "type": "shell",
            "command": "gradle",
            "args": ["run"],
            "group": {
                "kind": "test",
                "isDefault": true
            },
            "options": {"cwd" : "DungeoneerDesktop"}
        },
        {
            "label": "run editor",
            "type": "shell",
            "command": "gradle",
            "args": ["run"],
            "group": {
                "kind": "test",
                "isDefault": true
            },
            "options": {"cwd" : "DelvEdit"}
        }
    ]
}
```

**Comment by jmickle66666666** [comment]
@joshuaskelly Yeah I'd be happy to add this if/when the wiki gets started

**Comment by joshuaskelly** [comment]
I've added basic build instructions to the wiki (thanks for the help):
https://github.com/Interrupt/delverengine/wiki/Build-Instructions

We can add sub-pages for specific build environments. Depends on what folks feel up to doing. :)

**Comment by PythooonUser** [comment]
@jmickle66666666 Hey, just wondering - could you also set up the debugger in VS Code? I have some issues with that. And I'm using that Java extension by RedHat.

**Comment by PythooonUser** [comment]
Nevermind. Got it working with #74.
