### ISSUE TITLE
Arrows sometimes passing through monsters

### ISSUE THREAD

**Issue by hemebond** [Interrupt/delverengine#139]
Sometimes it seems to be impossible to hit a monster with arrows as the arrows will pass through them.

**Comment by PythooonUser** [comment]
Actually I noticed this with wands as well. The collision box of monster might be smaller than the sprite?

**Comment by PythooonUser** [comment]
@joshuaskelly I think this has been fixed with the recent upate?

**Comment by joshuaskelly** [comment]
Yep! Thank you for looking over the issues.

Fixed with #198
