### ISSUE TITLE
Models Inside of Group Don't Render Correctly In Editor

### ISSUE THREAD

**Issue by joshuaskelly** [Interrupt/delverengine#146]
![delvedit-group-model-render-issue](https://user-images.githubusercontent.com/372642/96518165-29d45700-121f-11eb-9230-0ad6903dd394.gif)

# Summary
After opening a level a group containing a model doesn't not render as expected. It will not show unless the cursor is hovering over it. After duplicating any object (alt drag) it will render correctly.

## Note
It does render correctly when in play mode, this only impacts editor mode.

**Comment by PythooonUser** [comment]
Yes! Same behavior found in #136.
