### ISSUE TITLE
Camera messed up when toggling simulation in DevlEdit

### ISSUE THREAD

**Issue by NetherNarwhal** [Interrupt/delverengine#23]
After the fly controls were implemented it exposed weird behaviour when toggling between simulation. Hitting 'P' plays the level, but you are facing up toward the sky. Hitting 'Esc' takes you back to edit, but you are now looking down at the ground.

I have a fix, but GitHub managing forks via the UI has cluttered my commit history so much I'll spare you the messed up PR that will result. The fix is pretty simple. In `EditorFrame`, make the following changes to get rid of adding/subtracting the unnecessary 18.9f to things:

Change Line 471 to `rotY = -Game.instance.player.yrot;`
Change Line 2380 to `Game.instance.player.yrot = -rotY;`

You may also want to change Line 2378 to `Game.instance.player.z = camera.position.y - 0.5f;` to match the height being set the other way (they are both +/- 0.5f now).

**Comment by Interrupt** [comment]
Looks like this fix was included in with your Sky tesselation fixes, so you may have already done this work :D

**Comment by NetherNarwhal** [comment]
That it does. Not sure what happened there. I tried to create a new PR and it apparently added it in the one that was already open. Weird. I guess this issue can be closed then.
