### ISSUE TITLE
Raspberry Pi version

### ISSUE THREAD

**Issue by hmlendea** [Interrupt/delverengine#3]
Hello,

Does anyone know if this can be compiled for ARM? I see that it's Java so it shouldn't be a problem unless they used some third party proprietary stuff that's not available on other platforms, right?

I'd also like to know the system requirements for running the game. I'm curious to see if it would be able to run on a Pi 3 hardware.
Publishing them in the README.md would be quite helpful, by the way.

**Comment by joshuaskelly** [comment]
Closing as this is more of a question than a bug/feature request.
