### ISSUE TITLE
Find a licence that works better for games than GPL-2.0

### ISSUE THREAD

**Issue by Interrupt** [Interrupt/delverengine#6]
GPL-2.0 might not be the best choice for this as a game engine. Ideally we can find something that can do the following:

- Let people use the engine for free and commercial projects
- Require people to make any engine changes made for their projects available
- Not require people to release assets or code specific to their project that does not change the base engine

**Comment by HeadClot** [comment]
Maybe this would work? 

https://en.wikipedia.org/wiki/Affero_General_Public_License

**Comment by Interrupt** [comment]
For now I switched to a simpler licence based on the very simple zLib licence: https://github.com/Interrupt/delverengine/blob/master/LICENSE.txt

If something better comes along we can use that, the closest I found to a good licence to use was the Mozilla Publice Licence v2.0 but I still don't totally understand all of the ramifications of that.

**Comment by pudarida** [comment]
MOZILLA-2.0 is like GPL, but the code can be mixed with proprietary code eg. dual licensed. This will allow people to keep certain parts of their fork proprietary while keeping the rest open-source. I don't like this, I prefer GPL as it will allow every future fork/mod of the engine to support each other, proprietary. A good of example of a big ecosystem around a GPL-licensed game engine is the original DOOM, only the code is licensed under GPL, but the game's asset is not.

I think the best way to prevent GPL from affecting the game asset is to remove all of the assets that are currently in this engine's repo and then put it on its own repository under a different license. The new repo, containing minimal assets enough to run the engine, will serve as a reference or template when making games for the Delver engine.

**Comment by Calinou** [comment]
I would suggest using something like the MPLv2 that follows the [Open Source Definition](https://opensource.org/osd/), rather than a custom license.

**Comment by joshuaskelly** [comment]
@Interrupt I see you've modified the license. Is this resolved, or is it still an open issue?

**Comment by Interrupt** [comment]
Current licence is a stopgap until we can find something better - still need to do more research and oh god this is a giant topic
