### ISSUE TITLE
Make Legacy Level Format In Load Dialog Optional

### ISSUE THREAD

**Issue by PythooonUser** [Interrupt/delverengine#80]
## Summary
The loading dialog shows files of type `.png` which are not level files. I would expect that the file picker only shows `.bin` and `.dat` files.

![grafik](https://user-images.githubusercontent.com/13063023/93940883-90a04680-fd2d-11ea-9140-15665d747100.png)

**Comment by joshuaskelly** [comment]
I believe that `.png`, `.dat`, and `.bin` are valid file formats.

**Comment by PythooonUser** [comment]
Interesting. But that kind of stands in contrast with #82. Here `.png` was not saved correctly.

**Comment by PythooonUser** [comment]
I would like to repurpose this issue to something else related to loading files. There is #79 that deals with the validation of loading files.

However, in contrast to my initial assumption `.png` are valid, but it's for an old level format. I think it would be great and less confusing to add a checkbox widget to the level loading dialog that says `Show legacy format` that is initially ticked off. Only when the user activates that checkbox, we would also show `.png` files.

As I understand from the Discord discussion there are not many people that use this legacy format anymore.

**Comment by PythooonUser** [comment]
Work In Progress:

![grafik](https://user-images.githubusercontent.com/13063023/94490394-7c08f600-01e6-11eb-92b7-bf99092f6c3f.png)
