### ISSUE TITLE
Selection Active When In Menu

### ISSUE THREAD

**Issue by PythooonUser** [Interrupt/delverengine#84]
## Summary
The tile selection still follows the mouse cursor even when hovering over the menu bar. I would expect the selection to be not active.

![top-menu-selection-wrong](https://user-images.githubusercontent.com/13063023/93943249-6a30da00-fd32-11ea-858e-8da147c10315.gif)

**Comment by joshuaskelly** [comment]
I believe it is trying to find the closest tile to the cursor. We could turn that off when the cursor is outside the bounds of the level?

**Comment by PythooonUser** [comment]
Yes, I think that would be more consistent. Could also be an option for #81.
