### ISSUE TITLE
Copy + Paste Places Item Under Floor

### ISSUE THREAD

**Issue by joshuaskelly** [Interrupt/delverengine#85]
![delvedit-copy+paste](https://user-images.githubusercontent.com/372642/93944908-b7895900-fcea-11ea-8629-7b3f8c2013f2.gif)

# Summary
Copy and paste is placing copy under floor instead of on it.

**Comment by PythooonUser** [comment]
Hey, can you give more info about the exact behavior that you want?

What comes to my mind:
- Copy placed at the floor
- Copy height kept the same
- Copy height offset kept the same

![grafik](https://user-images.githubusercontent.com/13063023/93979202-51014b00-fd7d-11ea-8e52-192f66d43e9f.png)

What about the handling of slopes? I could imaging that if copy from has a downwards slope, copy to has an upwards slope so the item could be stuck under the ground (if keeping height offset from `0.5f`).

![grafik](https://user-images.githubusercontent.com/13063023/93979667-ef8dac00-fd7d-11ea-9115-ef8df268ed55.png)
