### ISSUE TITLE
Emission Shader Incorrect

### ISSUE THREAD

**Issue by joshuaskelly** [Interrupt/delverengine#92]
![image](https://user-images.githubusercontent.com/372642/94071296-8707f480-fda8-11ea-93ce-d710e85cd3eb.png)
_Linear alpha gradient applied across center texture. Left actual. Right expected_

# Summary
The emission calculation in the main shader is correct because it is multiplying the already pre-multiplied color value by the inverse alpha which results in higher values actually getting darker (shown above on the left).

**Comment by PythooonUser** [comment]
I think this was fixed with #93, right?
