### ISSUE TITLE
Pressing T Key While Typing in Property Pane Rotates Entity

### ISSUE THREAD

**Issue by joshuaskelly** [Interrupt/delverengine#96]
# Summary
When typing in a text field in the entity property pane, pressing the t key will rotate the entity. This is not desirable.
The property pane should consume most keystrokes. Though exceptions might be made for ctrl + s, etc?

## Notes
Should be a similar to fix to preventing the camera from moving when scrolling in the entities pane:
https://github.com/Interrupt/delverengine/blob/e006725a977f07b0c24cc315d8560761f510210e/DelvEdit/src/com/interrupt/dungeoneer/editor/ui/EditorUi.java#L478

**Comment by evrimoztamur** [comment]
Encountered this while testing 3D text objects as well, same with R (rotate) etc.

This is likely going to be addressed in either EditorActions (where the commands are defined) or EditorUi constructor (where the EditorActions are used). Can also be managed with a new parameter to the MenuAccelerators.

**Comment by evrimoztamur** [comment]
Please review #111 as a resolution of this issue. Not entirely optimal as it changes key binding behaviour, however.

**Comment by PythooonUser** [comment]
I guess this issue can be closed as #111 has been merged?
